import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Spotlight from "@/components/ui/Spotlight";

const lato = Lato({ subsets: ["latin-ext"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={lato.className}>
        <div className={"relative min-h-screen bg-slate-900 text-slate-200"}>
          <Spotlight className="absolute inset-0" />
          {children}
        </div>
      </body>
    </html>
  );
}
